version: 0.2

run-as: DevopsUser

env:
  shell: bash
  variables:
    IMAGE_REPO_NAME: "sample-py-image"
    IMAGE_TAG: "latest"
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.9
    commands:
      - echo "Enabling docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    run-as: DevopsUser
    on-failure: ABORT
    commands:
      - echo "Logging into AWS ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    run-as: DevopsUser
    on-failure: ABORT
    commands:
      - echo "Build started on `date`"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f AWSCodepipeline/Dockerfile .
      - echo "Build completed on `date`"
  post_build:
    run-as: DevopsUser
    on-failure: ABORT
    commands:
      - echo "Pushing docker image to $IMAGE_REPO_NAME"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG