AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions

Parameters:
  AttributeNameValue:
    Type: String
    Description: Provide atrribute name for dynamo db table
Resources:
  Fn::ForEach::Tables:
    - TableName
    - [Points, Score]
    - DynamoDb${TableName}:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: !Ref TableName
          AttributeDefinitions:
            - AttributeName: !Ref AttributeNameValue
              AttributeType: S
          KeySchema:
            - AttributeName: !Ref AttributeNameValue
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'