version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting environment variables to tag image..."
      - echo "Logging into AWS ECR..."
      - aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ecr}
      # - command
  build:
    commands:
      - echo "Build completed on `date`"
      - docker build -t ${tag}:latest -f IaC-AWSCDK-Python/code_build/dockerImage/Dockerfile .
      - docker tag $tag:latest ${ecr}:${tag}
     #- command
  post_build:
    commands:
      - /bin/sh -c 'if [ $? -eq "0" ]; then echo "Build Successful on `date`"; else echo "Build failed"; fi'
      #- echo ""
      - docker push ${ecr}
